added Inheritance to the program
htmlacademy-ecmascript/1811791-big-trip-16 pull request #7
Opened 2021-12-07 23:17 UTC by Volnodoom

2021-12-08 18:45 UTC, slyvkanychmykyta requested changes

2021-12-08 18:45 UTC, slyvkanychmykyta commented on src/view/form/form-edit-view.js
> +    switch (type) {
а зачем тут проверка на тип?

2021-12-08 18:45 UTC, slyvkanychmykyta commented on src/view/form/form-edit-view.js
> +    switch (evt.target.getAttribute('data-btnClick')) {
и тут

2021-12-08 18:45 UTC, slyvkanychmykyta commented on src/view/form/form-edit-view.js
> +        this._callback.clickOnRollUpBtnForm = callback;
лучше было бы сократить до`this._callback.click = callback`

2021-12-09 16:47 UTC, Volnodoom commented on src/view/form/form-edit-view.js
> +    switch (type) {
В дальнейшем, добавиться обработчик по нажатию на кнопку предложения, на смену значка у точки и т.д

2021-12-09 16:57 UTC, slyvkanychmykyta approved these changes

2021-12-09 16:57 UTC, merged